### ISSUE TITLE
Building steps on the fly

### ISSUE THREAD

**Issue by maxwondercorn** [Matt-Jensen/ember-js-pdf#11]
First thanks for the addon, It's working nicely in one of my apps.  In a new app, I have a requirement where I don't want to create the steps until the user actually saves the PDF.

I'm not showing the PDF, I  just want to save the PDF as part of a table export component.  The user can change the table data (CRUD) or filter it before exporting. I can update the steps in the actions as I'm doing in my other application but the user may only oqccaiosnally  export the table.  

The tables can be quite large and I don't want the overhead of modifying/creating the steps every time the user does something.  I just want to populate steps when the user wants to do a PDF export.

I thought the onSave action was going to be the answer but that is called after addStepsToJsPdf does it work.  Without a pre add Steps hook is there a way to accomplish this?

**Comment by Matt-Jensen** [comment]
@maxwondercorn is there a way you could publish some code so I can see exactly the problem you're describing?

**Comment by maxwondercorn** [comment]
Since you really need to see a complete route, it's probably a bit much to just put snippets here but let I'll pull together an example together and publish to Github.  Thanks.

**Comment by Matt-Jensen** [comment]
Thanks Max!
