### ISSUE TITLE
Can't use splitTextToSize

### ISSUE THREAD

**Issue by schorke** [Matt-Jensen/ember-js-pdf#12]
Hi,

I didn't find how to use the `splitTextToSize` command with text. Do you have any example on how to use it ? Okay, I can add it to steps but in jsPDF examples, they split the text with `splitTextToSize` and then set it into the `text` => [see here](https://rawgit.com/MrRio/jsPDF/master/) in `string splitting`.

Is there any way to return the values from steps ?

Thanks !

**Comment by Matt-Jensen** [comment]
> I didn't find how to use the splitTextToSize command with text
```js
var textLines = doc
	.setFont('helvetica', 'neue')
	.setFontSize(fontSize)
	.splitTextToSize(text, maxLineWidth);
```

Becomes:
```js
var steps = [
    {setFont:['helvetica', 'neue']},
    {setFontSize: fontSize},
    {splitTextToSize: [text, maxLineWidth]}
]
```

> Is there any way to return the values from steps ?

There is not, currently, no.

**Comment by schorke** [comment]
Thanks I’ll try tomorrow! I'll keep you in touch

**Comment by schorke** [comment]
From what I understand, having only the step `{ splitTextToSize: [ text, maxLineWidth ] }` will not display anything => we have to use the step `{ text: [X, Y, mySplittedText ] }` to display it...

Like the example from jsPDF (last line) :
```
var textLines = doc
	.setFont('helvetica', 'neue')
	.setFontSize(fontSize)
	.splitTextToSize(text, maxLineWidth);

// doc.text can now add those lines easily; otherwise, it would have run text off the screen!
doc.text(textLines, margin, margin + 2 * oneLineHeight);
```
So I don't think your command `splitTextToSize` is useful at all ?

Thanks !

**Comment by Matt-Jensen** [comment]
Sorry to hear that
