### ISSUE TITLE
Orientation, Unit, Format, and CompressPdf

### ISSUE THREAD

**Issue by 0000marcell** [Matt-Jensen/ember-js-pdf#4]
Hi Matt, thanks for the addon, is there a way to change orientation in the current API ?

**Comment by Matt-Jensen** [comment]
Question: do you want to change the orientation of the PDF document or the PDF viewer?

**Comment by 0000marcell** [comment]
I wanna change the constructor options of the jsPDF object like "unit", "orientation", "format" etc...
my final goal is to print the page in landscape without the need to change anything.

**Comment by Matt-Jensen** [comment]
Got it, yep that's definitely a must have.  I'll add that feature ASAP.  If you have to fork in the mean time please let me know what you come up with.

**Comment by 0000marcell** [comment]
I think it's pretty easy to implement it, just including an opts argument will solve the problem, 
```
{{js-pdf steps opts=opts}} 
```
and then you can configure the opts in the controller.
